# Generated by Django 4.1 on 2023-10-08 23:42

import cosecheros.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cosechero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("apellido", models.CharField(max_length=255)),
                (
                    "cedula",
                    models.CharField(
                        max_length=13,
                        unique=True,
                        validators=[cosecheros.models.validate_cedula],
                    ),
                ),
                ("direccion", models.TextField()),
                ("telefono", models.CharField(max_length=20)),
                (
                    "terreno_sembrado",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Cantidad de terreno sembrado en tareas",
                        max_digits=10,
                    ),
                ),
            ],
        ),
    ]
