# Generated by Django 4.1 on 2023-10-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cosecheros", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cosechero",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="cosechero",
            name="numero_cuenta_banco",
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
