# Generated by Django 4.2.6 on 2024-01-30 01:07

import cosecheros.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cosecheros", "0002_cosechero_is_active_cosechero_numero_cuenta_banco"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cosechero",
            name="cedula",
            field=models.CharField(
                blank=True,
                max_length=13,
                validators=[cosecheros.models.validate_cedula],
            ),
        ),
    ]
