# Generated by Django 4.2.6 on 2024-01-30 01:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cosecheros", "0003_alter_cosechero_cedula"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cosechero",
            name="telefono",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
