# Generated by Django 4.2 on 2024-06-20 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cosecheros", "0004_alter_cosechero_telefono"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriaTabaco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "variedad",
                    models.CharField(
                        choices=[
                            ("Corojo Original", "Corojo Original"),
                            ("Corojo 99", "Corojo 99"),
                            ("Habano 92", "Habano 92"),
                            ("Criollo 98", "Criollo 98"),
                            ("Piloto Mejorado", "Piloto Mejorado"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("Centro Largo", "Centro Largo"),
                            ("Centro Corto", "Centro Corto"),
                            ("Uno y Medio", "Uno y Medio"),
                            ("Libre Pie", "Libre Pie"),
                            ("Picadura", "Picadura"),
                            ("Rezago", "Rezago"),
                            ("Criollo", "Criollo"),
                        ],
                        max_length=20,
                    ),
                ),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="EntregaTabaco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.DecimalField(decimal_places=2, max_digits=10)),
                ("fecha", models.DateField(auto_now_add=True)),
                (
                    "categoria_tabaco",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cosecheros.categoriatabaco",
                    ),
                ),
                (
                    "cosechero",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cosecheros.cosechero",
                    ),
                ),
            ],
        ),
    ]
