# Generated by Django 4.2 on 2024-06-20 23:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("cosecheros", "0005_categoriatabaco_entregatabaco"),
    ]

    operations = [
        migrations.RenameField(
            model_name="entregatabaco",
            old_name="fecha",
            new_name="fecha_entrega",
        ),
        migrations.RemoveField(
            model_name="entregatabaco",
            name="cantidad",
        ),
        migrations.RemoveField(
            model_name="entregatabaco",
            name="categoria_tabaco",
        ),
        migrations.AddField(
            model_name="entregatabaco",
            name="centro_corto",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="entregatabaco",
            name="centro_largo",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="entregatabaco",
            name="criollo",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="entregatabaco",
            name="libre_pie",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="entregatabaco",
            name="picadura",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="entregatabaco",
            name="rezago",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="entregatabaco",
            name="uno_medio",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="entregatabaco",
            name="variedad",
            field=models.CharField(
                choices=[
                    ("corojo_original", "Corojo Original"),
                    ("corojo_99", "Corojo 99"),
                    ("habano_92", "Habano 92"),
                    ("criollo_98", "Criollo 98"),
                    ("piloto_mejorado", "Piloto Mejorado"),
                ],
                default=django.utils.timezone.now,
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="CategoriaTabaco",
        ),
    ]
