# Generated by Django 4.2 on 2024-06-20 23:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cosecheros", "0006_rename_fecha_entregatabaco_fecha_entrega_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entregatabaco",
            name="fecha_entrega",
            field=models.DateField(),
        ),
    ]
