# Generated by Django 4.2 on 2024-06-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cosecheros", "0007_alter_entregatabaco_fecha_entrega"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entregatabaco",
            name="variedad",
            field=models.CharField(
                choices=[
                    ("Corojo Original", "Corojo Original"),
                    ("Corojo 99", "Corojo 99"),
                    ("Habano 92", "Habano 92"),
                    ("Criollo 98", "Criollo 98"),
                    ("Piloto Mejorado", "Piloto Mejorado"),
                ],
                max_length=20,
            ),
        ),
    ]
