# Generated by Django 4.2 on 2024-06-22 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cosecheros", "0008_alter_entregatabaco_variedad"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entregatabaco",
            name="centro_corto",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="entregatabaco",
            name="centro_largo",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="entregatabaco",
            name="criollo",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="entregatabaco",
            name="libre_pie",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="entregatabaco",
            name="picadura",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="entregatabaco",
            name="rezago",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="entregatabaco",
            name="uno_medio",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
