# Generated by Django 4.2 on 2024-09-07 20:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cosecheros", "0009_alter_entregatabaco_centro_corto_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cosecha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=35, unique=True)),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField()),
            ],
        ),
    ]
