# Generated by Django 4.2.23 on 2026-07-19 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cosecheros", "0011_entregatabaco_cosecha"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entregatabaco",
            name="variedad",
            field=models.CharField(
                choices=[
                    ("Corojo Original", "Corojo Original"),
                    ("Corojo 99", "Corojo 99"),
                    ("Habano 92", "Habano 92"),
                    ("Criollo 98", "Criollo 98"),
                    ("Piloto Mejorado", "Piloto Mejorado"),
                    ("HVA", "HVA"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="PrecioVariedadCosecha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "variedad",
                    models.CharField(
                        choices=[
                            ("Corojo Original", "Corojo Original"),
                            ("Corojo 99", "Corojo 99"),
                            ("Habano 92", "Habano 92"),
                            ("Criollo 98", "Criollo 98"),
                            ("Piloto Mejorado", "Piloto Mejorado"),
                            ("HVA", "HVA"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "precio_centro_largo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "precio_centro_corto",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "precio_uno_medio",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "precio_libre_pie",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "precio_picadura",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "precio_rezago",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "precio_criollo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "cosecha",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="precios",
                        to="cosecheros.cosecha",
                    ),
                ),
            ],
            options={
                "verbose_name": "Precio de variedad por cosecha",
                "verbose_name_plural": "Precios de variedad por cosecha",
                "unique_together": {("cosecha", "variedad")},
            },
        ),
    ]
