# Generated by Django 4.2.23 on 2025-12-06 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cosecheros", "0011_entregatabaco_cosecha"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entregatabaco",
            name="variedad",
            field=models.CharField(
                choices=[
                    ("Corojo Original", "Corojo Original"),
                    ("Corojo 99", "Corojo 99"),
                    ("Habano 92", "Habano 92"),
                    ("Criollo 98", "Criollo 98"),
                    ("Piloto Mejorado", "Piloto Mejorado"),
                    ("HVA", "HVA"),
                ],
                max_length=20,
            ),
        ),
    ]
