# Generated by Django 4.2.23 on 2026-07-19 03:55
"""
Data migration: siembra PrecioVariedadCosecha para todas las cosechas
existentes usando los valores que hasta ahora estaban hardcodeados en
cosecheros/views.py y cosecheros/utils/reportes.py (PRECIOS_VARIEDAD).

Esto preserva exactamente los mismos totales en los reportes ya
generados — a partir de aquí los precios se editan desde la página
"Precios" (o el admin) y pueden variar libremente por cosecha.
"""
from decimal import Decimal

from django.db import migrations

# Orden posicional idéntico al que usaba el código original:
# Centro Largo, Centro Corto, Uno y Medio, Libre Pie, Picadura, Rezago, Criollo
PRECIOS_VARIEDAD = {
    'Corojo Original': [12000, 12000, 9000, 4000, 3000, 3000, 2500],
    'Corojo 99': [12000, 12000, 9000, 4500, 3000, 3000, 2500],
    'Habano 92': [12000, 12000, 9000, 4500, 3000, 3000, 2500],
    'Criollo 98': [12000, 12000, 9000, 4500, 3000, 3000, 2500],
    'Piloto Mejorado': [12000, 12000, 9000, 4500, 3000, 3000, 2500],
    'HVA': [12000, 12000, 9000, 4500, 3000, 3000, 2500],
}

CAMPOS_PRECIO = [
    'precio_centro_largo', 'precio_centro_corto', 'precio_uno_medio',
    'precio_libre_pie', 'precio_picadura', 'precio_rezago', 'precio_criollo',
]


def seed_precios(apps, schema_editor):
    Cosecha = apps.get_model('cosecheros', 'Cosecha')
    PrecioVariedadCosecha = apps.get_model('cosecheros', 'PrecioVariedadCosecha')

    for cosecha in Cosecha.objects.all():
        for variedad, precios in PRECIOS_VARIEDAD.items():
            valores = {
                campo: Decimal(str(valor))
                for campo, valor in zip(CAMPOS_PRECIO, precios)
            }
            PrecioVariedadCosecha.objects.get_or_create(
                cosecha=cosecha, variedad=variedad, defaults=valores,
            )


def noop(apps, schema_editor):
    # No se revierte automáticamente: borrar precios ya en uso por
    # reportes sería más peligroso que dejarlos.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("cosecheros", "0012_precio_variedad_cosecha"),
    ]

    operations = [
        migrations.RunPython(seed_precios, noop),
    ]
