# Generated by Django 4.2.6 on 2023-10-22 21:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articulo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articulo",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("abonos", "Abonos"),
                    ("fungicidas", "Fungicidas"),
                    ("insecticidas", "Insecticidas"),
                ],
                default="Abonos",
                max_length=50,
            ),
        ),
    ]
