# Generated by Django 4.2.6 on 2024-01-29 22:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("articulo", "0002_alter_articulo_categoria"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="articulo",
            name="cantidad",
        ),
        migrations.RemoveField(
            model_name="articulo",
            name="codigo",
        ),
        migrations.RemoveField(
            model_name="articulo",
            name="precio_compra",
        ),
        migrations.RemoveField(
            model_name="articulo",
            name="precio_venta",
        ),
    ]
