# Generated by Django 4.2 on 2024-03-02 23:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articulo", "0003_remove_articulo_cantidad_remove_articulo_codigo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articulo",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("abonos", "Abonos"),
                    ("fungicidas", "Fungicidas"),
                    ("insecticidas", "Insecticidas"),
                    ("coadyudantes", "Coadyudantes"),
                ],
                default="Abonos",
                max_length=50,
            ),
        ),
    ]
