# Generated by Django 4.2 on 2024-03-02 23:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articulo", "0004_alter_articulo_categoria"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articulo",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("abonos", "Abonos"),
                    ("fungicidas", "Fungicidas"),
                    ("insecticidas", "Insecticidas"),
                    ("coadyudantes", "Coadyudantes"),
                    ("herbicidas", "Herbicidas"),
                ],
                default="Abonos",
                max_length=50,
            ),
        ),
    ]
