# Generated by Django 4.1 on 2023-10-22 21:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("avance", "0002_avance_remove_deposito_cosechero_and_more"),
        ("articulo", "0001_initial"),
        ("cosecheros", "0002_cosechero_is_active_cosechero_numero_cuenta_banco"),
        ("ventas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DetalleArticulo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveIntegerField()),
                (
                    "precio_venta_final",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "articulo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="articulo.articulo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DetalleAvance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "avance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="avance.avance"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="venta",
            name="fecha_venta",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="venta",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="venta",
            name="total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="venta",
            name="cosechero",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cosecheros.cosechero"
            ),
        ),
        migrations.DeleteModel(
            name="DetalleVenta",
        ),
        migrations.AddField(
            model_name="detalleavance",
            name="venta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detalle_avances",
                to="ventas.venta",
            ),
        ),
        migrations.AddField(
            model_name="detallearticulo",
            name="venta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detalle_articulos",
                to="ventas.venta",
            ),
        ),
    ]
