# Generated by Django 4.2 on 2024-03-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ventas", "0002_detallearticulo_detalleavance_venta_fecha_venta_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="venta",
            name="impreso",
            field=models.BooleanField(default=False),
        ),
    ]
