# Generated by Django 4.2 on 2024-03-30 18:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ventas", "0003_venta_impreso"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venta",
            name="fecha_venta",
            field=models.DateField(),
        ),
    ]
