# Generated by Django 4.2 on 2024-09-07 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cosecheros", "0011_entregatabaco_cosecha"),
        ("ventas", "0004_alter_venta_fecha_venta"),
    ]

    operations = [
        migrations.AddField(
            model_name="venta",
            name="cosecha",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ventas",
                to="cosecheros.cosecha",
            ),
            preserve_default=False,
        ),
    ]
