# Generated by Django 4.2.23 on 2026-08-08 23:28

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ventas", "0005_venta_cosecha"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detallearticulo",
            name="cantidad",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.CreateModel(
            name="OperacionVenta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "clave",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("fecha_movimiento", models.DateField()),
                ("creada_en", models.DateTimeField(auto_now_add=True)),
                ("huella_payload", models.CharField(max_length=64)),
                (
                    "total_movimiento",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("impresion_solicitada", models.BooleanField(default=False)),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="operaciones_venta",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "venta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operaciones",
                        to="ventas.venta",
                    ),
                ),
            ],
            options={
                "ordering": ("-creada_en",),
            },
        ),
        migrations.AddField(
            model_name="detallearticulo",
            name="operacion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="detalles_articulo",
                to="ventas.operacionventa",
            ),
        ),
        migrations.AddField(
            model_name="detalleavance",
            name="operacion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="detalles_avance",
                to="ventas.operacionventa",
            ),
        ),
    ]
