# Generated by Django 4.1 on 2023-10-16 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cosecheros", "0002_cosechero_is_active_cosechero_numero_cuenta_banco"),
    ]

    operations = [
        migrations.CreateModel(
            name="PagoEfectivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monto_pagado", models.DecimalField(decimal_places=2, max_digits=10)),
                ("fecha", models.DateField()),
                ("descripcion", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "cosechero",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cosecheros.cosechero",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Deposito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monto_pagado", models.DecimalField(decimal_places=2, max_digits=10)),
                ("fecha", models.DateField()),
                ("descripcion", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "cosechero",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cosecheros.cosechero",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Cheque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monto_pagado", models.DecimalField(decimal_places=2, max_digits=10)),
                ("fecha", models.DateField()),
                ("descripcion", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("numero_cheque", models.CharField(max_length=255)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("realizado", "Realizado"),
                            ("cambiado", "Cambiado"),
                            ("nulo", "Nulo"),
                        ],
                        default="realizado",
                        max_length=10,
                    ),
                ),
                (
                    "cosechero",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cosecheros.cosechero",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
