# Generated by Django 4.1 on 2023-10-22 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cosecheros", "0002_cosechero_is_active_cosechero_numero_cuenta_banco"),
        ("avance", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Avance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monto_pagado", models.DecimalField(decimal_places=2, max_digits=10)),
                ("fecha", models.DateField()),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "tipo_avance",
                    models.CharField(
                        choices=[
                            ("cheque", "Cheque"),
                            ("deposito", "Deposito"),
                            ("efectivo", "Pago Efectivo"),
                        ],
                        max_length=10,
                    ),
                ),
                ("numero", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("realizado", "Realizado"),
                            ("cambiado", "Cambiado"),
                            ("nulo", "Nulo"),
                        ],
                        default="realizado",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "cosechero",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cosecheros.cosechero",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="deposito",
            name="cosechero",
        ),
        migrations.RemoveField(
            model_name="pagoefectivo",
            name="cosechero",
        ),
        migrations.DeleteModel(
            name="Cheque",
        ),
        migrations.DeleteModel(
            name="Deposito",
        ),
        migrations.DeleteModel(
            name="PagoEfectivo",
        ),
    ]
