# Generated by Django 4.1 on 2023-10-16 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("articulo", "0001_initial"),
        ("proveedor", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Compra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_compra", models.DateField()),
                ("fecha_vencimiento", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="DetalleCompra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveIntegerField()),
                ("cantidad_restante", models.PositiveIntegerField(default=0)),
                ("precio_compra", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "precio_venta_sugerido",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "articulo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="articulo.articulo",
                    ),
                ),
                (
                    "compra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="compra.compra"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="compra",
            name="articulos",
            field=models.ManyToManyField(
                through="compra.DetalleCompra", to="articulo.articulo"
            ),
        ),
        migrations.AddField(
            model_name="compra",
            name="proveedor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="proveedor.proveedor"
            ),
        ),
    ]
