# Generated by Django 4.2.6 on 2024-02-04 05:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("compra", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="detallecompra",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
