# Generated by Django 4.2 on 2024-03-02 22:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("compra", "0002_detallecompra_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="compra",
            name="NFC",
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="compra",
            name="factura",
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
    ]
