# Generated by Django 4.2 on 2024-03-09 21:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("proveedor", "0001_initial"),
        ("compra", "0003_compra_nfc_compra_factura"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="compra",
            unique_together={("proveedor", "factura")},
        ),
    ]
