# Generated by Django 4.2 on 2024-06-04 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("compra", "0004_alter_compra_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detallecompra",
            name="cantidad",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="detallecompra",
            name="cantidad_restante",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
